apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/hoyon/argo-test-app
      revision: HEAD
      files:
      - path: "configs/**/config.json"
  template:
    metadata:
      name: '{{.name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/stefanprodan/podinfo.git
        targetRevision: HEAD
        path: charts/podinfo
      destination:
        server: "https://kubernetes.default.svc"
        namespace: guestbook
