apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hoyon/argo-test-app
    path: rollout-test
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
