apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-test
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: rollout-test-active
      previewService: rollout-test-preview
      autoPromotionEnabled: true
  selector:
    matchLabels:
      app: rollout-test
  template:
    metadata:
      labels:
        app: rollout-test
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:green
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
